# Generated by Django 5.1.1 on 2024-12-05 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_libro_isbn_almacen_libro_almacen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='propietario',
            new_name='usuario',
        ),
    ]
