# Generated by Django 5.1.1 on 2024-12-10 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_rename_propietario_libro_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='usuario',
            new_name='propietario',
        ),
    ]
