# Generated by Django 5.1.1 on 2024-12-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_rename_usuario_libro_propietario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacen',
            name='nombre',
        ),
    ]
