# Generated by Django 5.1.1 on 2024-12-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_almacen_usuario'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='libro',
            name='unique_isbn_per_user',
        ),
        migrations.AlterUniqueTogether(
            name='libro',
            unique_together={('almacen', 'isbn')},
        ),
    ]
