# Generated by Django 5.1.1 on 2024-12-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_remove_libro_unique_isbn_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='codigo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
