# Generated by Django 5.1.1 on 2024-12-15 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_almacen_codigo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prestamo',
        ),
    ]
