# Generated by Django 5.1.1 on 2024-12-15 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_delete_prestamo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntuacionlibro',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.libro'),
        ),
        migrations.AlterField(
            model_name='puntuacionlibro',
            name='puntuacion',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='puntuacionlibro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='puntuacionlibro',
            unique_together={('libro', 'usuario')},
        ),
    ]
