# Generated by Django 5.1.1 on 2024-12-15 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_puntuacionlibro_libro_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PuntuacionLibro',
        ),
    ]
