# Generated by Django 5.1.1 on 2024-12-16 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_puntuacionlibro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='en_prestamo',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='fecha_prestamo',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='usuario_prestamo',
        ),
        migrations.CreateModel(
            name='LibreriaLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('autor', models.CharField(blank=True, max_length=255, null=True)),
                ('edicion', models.CharField(blank=True, max_length=255, null=True)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='librerialibros', to='gestion.almacen')),
            ],
        ),
    ]
