# Generated by Django 5.1.1 on 2024-12-16 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_remove_libro_en_prestamo_remove_libro_fecha_prestamo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librerialibro',
            name='almacen',
        ),
    ]
