# Generated by Django 5.1.1 on 2024-12-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_remove_librerialibro_almacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='librerialibro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='libros_portada/'),
        ),
    ]
